<?
abstract class PasswordReset {
	
	static function insertRequest($email) {
		// THIS FUNCTION INSERTS A PASSWORD RESET REQUEST INTO DATABASE AND IT SENDS AN EMAIL TO USER.
		// EVERY REQUEST HAS ITS RID GENERATED BY generateRID()
	}
	
	static function checkRequestExists($email, $rid) {
		// THIS FUNCTION DETERMINES THE EXISTENCE OF A REQUEST, GIVEN THE USER'S EMAIL AND RID RECEIVED ON THAT EMAIL.
		// IF THE REQUEST EXISTS, THE USER WILL BE GIVEN THE POSSIBILITY TO CHANGE HIS PASSWORD
	}
	
	static function changePsw($email, $rid, $new_psw) {
		if(self::checkRequestExists($email, $rid)) {
			// THE USER CAN NOW CHANGE HIS PASSWORD
		}
		return false;
	}
	
	// RID Generation 
	
	static function generateRID($_user) {
		// PRIVATE
	}
}
?>
